# -*- coding: utf-8 -*-
"""AntividadeContextualizada6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uO1Q3CcfcnsIJosGIyQoKhUiv0MIRQnk
"""



#Etapa I - Procedimento de anestesia:
print("Aperte 1 para sim e 2 para não\n")

Anestesia = input("Qual fármaco utilizado para anestesia?\n")
Holotano = int(input("Esse fármaco é utilizado em conjunto, halotano (gasoso)? aperte 1 para sim e 2 para não \n"))
if (Holotano == 1):
  print("Adicionar holonato")

dosagem_anestesia = int(input("A dosagem da anestesia está de acordo com o peso do animal? aperte 1 para sim e 2 para não \n"))

  print("Proxima etapa: posicionamento do animal")

#Etapa II - Posicionamento do animal
print("Aperte 1 para sim e 2 para não\n")

efeito_anestesia = int(input("A anestesia alcançou a efetividade?\n"))
if efeito_anestesia == 1 :
  print("posicionamento")
elif not efeito_anestesia == 2:
    print('aumentar a dose de anestésico') 
else:
    print('O rato é resistente a este anestésico, aplique novamente com a outra droga')
posicao_animal = int(input("O animal está posicionado no estereotáxico\n"))
posicao_barra = int(input("A barra de suporte está posicionada no ouvido externo do animal?"))
verificacao_angulacao = int(input("A cabeça do animal está posicionada corretamente? Para isso, não pode haver diferenças de angulação entre o bregma e o lambda\n"))
if (posicao_animal and posicao_barra and verificacao_angulacao) :
  print("Proxima etapa: Limpeza") 
elif not posicao_animal and posicao_barra and verificacao_angulacao :
  print("Verifique novamente as faeses da limepeza.")



#Etapa III - Limpeza
print("Realize os seguintes passos:")
dicionário_limpeza = {'retirar pelagem':(), 'retirar tecidos moles':('epiderme, derme, tecido conjuntivo'), 'limpar calota craniana':()}
for dicionário_limpeza in dicionário_limpeza:
    print(dicionário_limpeza) 

limpeza_realizada = int(input("Todos os passos da limpeza foram seguidos?\n"))
if limpeza_realizada == 1 :
  print("Próxima etapa: Poliacrilato")
elif not limpeza_realizada == 2 :
  print("Realiza todos os passos da limpeza.")

#Etapa IV- Poliacrilato
print("Com o animal posicionado, utilize uma pequena camada de poliacrilato em todo o perímetro externo para evitar sangramentos")
poliacrilato = int(input("O poliacrilato foi utilizado em todo perímetro?"))
if (poliacrilato) :
  print("Próxima etapa:Fixação dos parafusos.")

#Etapa V - Fixação dos parafusos
print("Escolha um ponto para a fixação de parafusos, de preferência na parte posterior da calota craniana.")
print("ATENÇÃO: Cuidar para não aprofundar muito o parafuso. Com parafusos maiores deve-se dar até 3 voltas no parafuso.")

print("Posicione a agulha sobre o bregma e medir com a régua a posição AnteroPosterior (AP), LateroLateral (LL) e DorsoVentral (DV)")
print("Preencha a seguir os valores encontrados")
ap= input("AP: ")
ll= input("LLesq: ")
ll= input("LLdir: ")
dv= input("DV: ")
print("com os valores encontrados, calcule com cada estrutura ou núcleo.")
print("AP - 0,42 ; LL1 - 0,30 ; LL2 + 0,30 ; DV - 0,20")
print("Digite os novos valores depois dos calculos")
apn= input("AP: ")
lln= input("LLesq: ")
lln= input("LLdir: ")
dvn= input("DV: ")

#Etapa VI - Ponto de inserção

print("Para os pontos de inserção da cânula guia, use os valores de AP  e os valores de LLesq e LLdir")
primeira_camara = input("Qual dos hemisférios vai ser colocada a primeira cânula? ")
print( "Proxima etapa")

#Etapa VII/VIII/IX - perfuração, canula, drenagem.


per_canu_drena = ['perfurar crânio a 45º de inclinação',' introduzir cânula até DV 4.00', 'drenar sangue ou LCR do orifício criado']
print(per_canu_drena)

#Etapa X - Acrílico polimizante
print("Faça uma mistura do acrílico polimerizante com o solvente suficiente para cobrir o cranio.")

#Etapa XI -FIXAÇÃO CANULA GUIA

print("levante o braço do estereotáxico lentamente e o posicione sobre o outro ponto de inserção da canula, introdui-la até DV 4,00")
while LLesq or LLdir == True:
  print('Repetir procedimentos no outro hemisfério', = per_canu_drena)
    break

#Etapa XII - Caixa-moradia
print("Acomode o animal em caixa aquecida por lâmpada e sem outros animais, quando despertar colocá-lo de volta na sua caixa-moradia.")

#Fim do programa