# -*- coding: utf-8 -*-
"""AtividadeContextualizada3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RZie0Bh-YSSOFYxfcsITNQjgMs2Mkz8K
"""

#Atividade3
#a.	Crie as variáveis necessárias para que o programa funcione corretamente.
Resolução= 210
Velocidade= 100
Digitalização= 100
Iluminação = 160 
Profundidade= 50
Espessura= 100
Qualidade= 200
Contraste= 150
laser= 80
Janela= 70
Nome_Do_Usuario= input

#Mensagem inicial
print ("Olá! Este é um programa que tem por objetivo receber dados para utilização do microscópio confocal") 
Nome_Do_Usuario = input ("Qual seu nome? ")
print ("Em seguida, insira as infomações solicitadas")

#Soliitação de Informações
Resolução = input("Qual a resolução da imagem?")
print ("alteração da variável inserida?")
print (Resolução == Resolução)
Velocidade = input ("Qual a velocidade desejada?")
print ("alteração da variável inserida?")
print (Velocidade == Velocidade)
Digitalização = input ("Qual Digitalização desejada?")
print ("alteração da variável inserida?")
print (Digitalização == Digitalização)
Iluminação = input ("Qual Iluminação desejada?")
print ("alteração da variável inserida?")
print (Iluminação == Iluminação)
Profundidade = input ("Qual Profundidade desejada?")
print ("alteração da variável inserida?")
print (Profundidade == Profundidade)
Espessura = input ("Qual espessura desejada?")
print ("alteração da variável inserida?")
print (Profundidade == Profundidade)
Qualidade = input ("Qual a qualidade desejada?")
print ("alteração da variável inserida?")
print (Qualidade == Qualidade)
Contraste = input ("Qual o contraste desejado?")
print ("alteração da variável inserida?")
print (Contraste == Contraste)
laser = input ("Qual o laser desejado?")
print ("alteração da variável inserida?")
print (laser == laser)
Janela = input ("Qual a Janela desejada?")
print ("alteração da variável inserida?")
print (Janela == Janela)

#Conferir informações
print ("Confira as informaçções fornecidas")
print ("resolução selecionada: %s" %(Resolução))
print ("Velocidade selecionada: %s" %(Velocidade))
print ("Digitalização selecionada: %s" %(Digitalização))
print ("Iluminação selecionada: %s" %(Iluminação))
print ("Profundidade selecionada: %s" %(Profundidade))
print ("Espessura selecionada: %s" %(Espessura))
print ("Qualidade selecionada: %s" %(Qualidade))
print ("Contraste selecionado: %s" %(Contraste))
print ("Laser selecionado: %s" %(laser))
print ("Janela selecionada: %s" %(Janela))

# #Calibração
print (Nome_Do_Usuario,('para calibração, digite a primeira e a última letra do seu nome 10x'))
Calibração1 = input ("1. Primeira letra: ")
Calibração1 = input ("1. última letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("2. Primeira letra: ") 
Calibração1 = input ("2. última letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("3. Primeira letra: ")
Calibração1 = input ("3. última letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("4. Primeira letra: ")
Calibração1 = input ("4. última letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("5. Primeira letra: ") 
Calibração1 = input ("5. última letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração1))  
Calibração1 = input ("6. Primeira letra: ") 
Calibração1 = input ("6. última letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("7. Primeira letra: ")
Calibração1 = input ("7. última letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração1)) 
Calibração1 = input ("8. Primeira letra: ") 
Calibração1 = input ("8. última letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("9. Primeira letra: ") 
Calibração1 = input ("9. última letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração1))
Calibração1 = input ("10. Primeira letra: ") 
Calibração1 = input ("10.última letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração1))
 
print (Nome_Do_Usuario,('estamos quase lá! Para continuar a calibração, digite a segunda e a penúltima letra do seu nome 10x'))
Calibração2 = input ("1. Segunda letra: ")
Calibração2 = input ("1. penúltima letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("2. Segunda letra: ") 
Calibração2 = input ("2. penúltima letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("3. Segunda letra: ")
Calibração2 = input ("3. penúltima letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("4. Segunda letra: ")
Calibração2 = input ("4. penúltima letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("5. Segunda letra: ") 
Calibração2 = input ("5. penúltima letra: ")  
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("6. Segunda letra: ") 
Calibração2 = input ("6. penúltima letra: ") 
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("7. Segunda letra: ")
Calibração2 = input ("7. penúltima letra: ")  
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("8. Segunda letra: ") 
Calibração2 = input ("8. penúltima letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("9. Segunda letra: ") 
Calibração2 = input ("9. penúltima letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração2))
Calibração2 = input ("10. Segunda letra: ") 
Calibração2 = input ("10. penúltima letra: ")
print ("letras selecioandas selecionada: %s" %(Calibração2))

print ("A calibração foi finalizada")