# -*- coding: utf-8 -*-
"""AtividadeContextualizada4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18sacl_zfzjl5aL1K8uVaPkyPgJrYj6sp
"""

#Fase de Habituação
#i.	Se o animal está habituado, registrar em uma variável
animal_habituado = int(input("o animal já está habituado? Aperte --> 1 para sim e --> 2 para não \n"))
if (animal_habituado): 
  print("Animal habituado, então vamos iniciar o treinamento")

#Regime de Aproximação
# i.	Iniciar a variável com 30cm
# ii.	Se a variável de aproximação diminuiu (animal aproximou), liberar 0,5ml de rec
# iii.	Se animal tocou na barra 20x, retornar que o experimento passou para a próxima etapa

distancia_inicial = bool(input('O sagui está a 30cm de distância? Aperte -> 1-> Sim 2-> Não \n'))
if (distancia_inicial):
  print('Inicio')

aproximacao_do_animal = bool(input("Houve aproximação do animal? Aperte -> 1 para sim e ->2 para não \n"))
if (aproximacao_do_animal):
  print("liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("1ªx liberar de 0,5ml de recompensa")

  toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("2ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("3ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("4ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("5ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
11
print("6ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("7ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("8ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("9ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("10ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("11ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("12ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("13ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("14ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("15ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("14ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("15ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("16ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("17ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("18ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("19ªx liberar de 0,5ml de recompensa")

toque_na_barra = bool(input("O animal tocou na barra? Aperte -> 1 para sim e ->2 para não \n"))
if (toque_na_barra):
  print("20ªx liberar de 0,5ml de recompensa")
  print("Próxima fase do experimento")

# iv.	Se o som1 foi emitido e o animal tocou na barra esquerda, liberar 0,5ml de rec
# v.	Caso contrário não liberar nada
# vi.	Se o som2 foi emitido e o animal tocou na barra direita, liberar 0,5ml de rec
# vii.	Caso contrário não liberar nada
# viii.	Se o experimento foi realizado 50x em 30min, apresentar que o experimento seguirá para a próxima fase.

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

 toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")  

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

toque_na_barra_esq_ph = int(input("o animal tocou na barra esquerda ao som de phee? Aperte -> 1 para sim e -> 2 para não\n"))
if (toque_na_barra_esq_ph==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_esq_ph==2) :
  print( "não liberar recomepnsa")

toque_na_barra_dir_tr = int(input("o animal tocou na barra direita ao som de trill? Aperte -> 1 para sim e ->2 para não\n"))
if (toque_na_barra_dir_tr==1): 
  print("liberar de 0,5ml de recompensa")
elif (toque_na_barra_dir_tr==2) :
  print( "não liberar recomepnsa")

print("fim do programa").